export const carBrandsAndModels = [
  {
    brand: "Ford",
    models: [
      "Mustang", 
      "Fiesta", 
      "Focus", 
      "Explorer", 
      "F-150", 
      "Fusion", 
      "Edge", 
      "Escape", 
      "Expedition", 
      "Bronco", 
      "Ranger", 
      "Taurus", 
      "EcoSport", 
      "Transit", 
      "Maverick", 
      "Mustang Mach-E", 
      "GT", 
      "C-Max", 
      "Flex", 
      "Freestyle",
      "Contour",
      "Crown Victoria",
      "Escort",
      "Excursion",
      "Fairlane",
      "Falcon",
      "Five Hundred",
      "Freestar",
      "Granada",
      "GT40",
      "LTD",
      "Model A",
      "Model T",
      "Pinto",
      "Probe",
      "Tempo",
      "Thunderbird",
      "Windstar",
      "Zephyr"
    ]
  },
  {
    brand: "Chevrolet",
    models: [
      "Camaro", 
      "Silverado", 
      "Malibu", 
      "Impala", 
      "Tahoe", 
      "Suburban", 
      "Equinox", 
      "Traverse", 
      "Colorado", 
      "Blazer", 
      "Trax", 
      "Spark", 
      "Bolt EV", 
      "Sonic", 
      "Avalanche", 
      "Express", 
      "HHR", 
      "Monte Carlo", 
      "Orlando", 
      "Trailblazer",
      "Corvette",
      "Chevelle",
      "Cavalier",
      "S10",
      "Astro",
      "GMC Sierra",
      "Impala SS",
      "Malibu Maxx",
      "Volt",
      "Express 3500",
      "Suburban 2500",
      "Silverado HD",
      "Blazer EV",
      "Camaro ZL1",
      "Cobalt",
      "Tracker",
      "Sonic RS",
      "G20",
      "G30",
      "Caprice",
      "El Camino",
      "SSR",
      "Trailblazer SS"
    ]
  },
  {
    brand: "Toyota",
    models: [
      "Corolla", 
      "Camry", 
      "Prius", 
      "Highlander", 
      "RAV4", 
      "Avalon", 
      "Yaris", 
      "Sienna", 
      "Tacoma", 
      "Tundra", 
      "Venza", 
      "Sequoia", 
      "4Runner", 
      "Land Cruiser", 
      "Mirai", 
      "Supra", 
      "C-HR", 
      "Matrix", 
      "Celica", 
      "MR2",
      "Hilux",
      "Land Cruiser Prado",
      "Corolla Cross",
      "Sienta",
      "Aygo",
      "Dyna",
      "HiAce",
      "Tundra TRD Pro",
      "RAV4 Prime",
      "C-HR Hybrid",
      "Camry Hybrid",
      "Avalon Hybrid",
      "Sienna Hybrid",
      "Mirai Hydrogen",
      "Supra GR",
      "Yaris Cross",
      "Crown",
      "Vitz",
      "Tercel",
      "Echo",
      "Solara",
      "Previa",
      "FJ Cruiser",
      "Sequoia TRD Pro"
    ]
  },
  {
    brand: "Honda",
    models: [
      "Civic", 
      "Accord", 
      "CR-V", 
      "Pilot", 
      "Fit", 
      "HR-V", 
      "Odyssey", 
      "Ridgeline", 
      "Insight", 
      "Passport", 
      "Element", 
      "S2000", 
      "Prelude", 
      "CR-Z", 
      "Crosstour", 
      "Clarity", 
      "FR-V", 
      "Jazz", 
      "Legend", 
      "Shuttle",
      "HR-V Hybrid",
      "Civic Type R",
      "Accord Hybrid",
      "CR-V Hybrid",
      "Pilot Elite",
      "Fit EV",
      "Odyssey Elite",
      "Ridgeline Black Edition",
      "Insight Touring",
      "Passport Elite",
      "Element SC",
      "S2000 CR",
      "Prelude Si",
      "CR-Z Sport",
      "Crosstour EX-L",
      "Clarity Plug-In Hybrid",
      "FR-V 1.7",
      "Jazz Crosstar",
      "Legend Coupe",
      "Shuttle Hybrid"
    ]
  },
  {
    brand: "BMW",
    models: [
      "Serie 3", 
      "Serie 5", 
      "Serie 7", 
      "Serie 1", 
      "Serie 2", 
      "Serie 4", 
      "Serie 6", 
      "Serie 8", 
      "X1", 
      "X2", 
      "X3", 
      "X4", 
      "X5", 
      "X6", 
      "X7", 
      "i3", 
      "i8", 
      "Z4", 
      "M2", 
      "M3", 
      "M4", 
      "M5", 
      "M6", 
      "M8",
      "M1",
      "M4 GTS",
      "M5 Competition",
      "X8",
      "X3 M",
      "X4 M",
      "Z3",
      "Z8",
      "iX",
      "i4",
      "iX3",
      "M8 Competition",
      "M850i",
      "X7 M50i",
      "X5 M",
      "X6 M",
      "M3 Touring",
      "M4 CSL"
    ]
  },
  {
    brand: "Mercedes-Benz",
    models: [
      "Classe A", 
      "Classe B", 
      "Classe C", 
      "Classe E", 
      "Classe S", 
      "CLA", 
      "CLS", 
      "GLA", 
      "GLB", 
      "GLC", 
      "GLE", 
      "GLS", 
      "G-Class", 
      "EQC", 
      "EQA", 
      "EQB", 
      "EQE", 
      "EQS", 
      "AMG GT", 
      "AMG GT 4-Door", 
      "SLC", 
      "SL", 
      "V-Class", 
      "X-Class", 
      "Sprinter",
      "AMG A 35", 
      "AMG A 45", 
      "AMG C 43", 
      "AMG C 63", 
      "AMG E 53", 
      "AMG E 63", 
      "AMG G 63", 
      "AMG GLE 53", 
      "AMG GLE 63", 
      "AMG GLC 43", 
      "AMG GLC 63", 
      "AMG S 63", 
      "AMG S 65", 
      "AMG SL 55", 
      "AMG SL 63", 
      "Citan", 
      "Vito", 
      "Marco Polo", 
      "EQS SUV", 
      "EQB SUV", 
      "EQC SUV", 
      "E-Class Coupe", 
      "E-Class Cabriolet", 
      "S-Class Coupe", 
      "S-Class Cabriolet"
    ]
  },
  {
    brand: "Audi",
    models: [
      "A1", 
      "A3", 
      "A4", 
      "A5", 
      "A6", 
      "A7", 
      "A8", 
      "Q2", 
      "Q3", 
      "Q5", 
      "Q7", 
      "Q8", 
      "TT", 
      "R8", 
      "e-tron", 
      "RS3", 
      "RS4", 
      "RS5", 
      "RS6", 
      "RS7", 
      "RS Q3", 
      "RS Q8", 
      "S3", 
      "S4", 
      "S5", 
      "S6", 
      "S7", 
      "S8", 
      "Q4", 
      "Q5 e-tron", 
      "Q6", 
      "Q8 e-tron", 
      "A2", 
      "A9", 
      "A1 Sportback", 
      "A3 Sportback", 
      "A4 Avant", 
      "A5 Sportback", 
      "A6 Avant", 
      "A7 Sportback", 
      "A8 L", 
      "S1", 
      "S2", 
      "S4 Avant", 
      "S5 Sportback", 
      "S6 Avant", 
      "S8 Plus", 
      "RS Q5", 
      "RS Q7", 
      "RS Q8"
    ]
  },
  {
    brand: "Volkswagen",
    models: [
      "Golf", 
      "Passat", 
      "Tiguan", 
      "Jetta", 
      "Polo", 
      "Beetle", 
      "Arteon", 
      "Atlas", 
      "CC", 
      "Eos", 
      "Fox", 
      "ID.3", 
      "ID.4", 
      "ID. Buzz", 
      "Scirocco", 
      "Sharan", 
      "T-Cross", 
      "T-Roc", 
      "Touran", 
      "Touareg", 
      "Up!",
      "Phaeton",
      "Tiguan Allspace",
      "ID.5",
      "ID.6",
      "ID. Buzz Cargo",
      "Lupo",
      "Polo GTI",
      "Golf GTI",
      "Golf R",
      "Arteon Shooting Brake",
      "Caddy",
      "Transporter",
      "Amarok",
      "T-Roc Cabriolet",
      "Taigo",
      "ID.4 GTX"
    ]
  },
  {
    brand: "Nissan",
    models: [
      "Altima", 
      "Sentra", 
      "Maxima", 
      "Rogue", 
      "Murano", 
      "Pathfinder", 
      "Armada", 
      "Versa", 
      "Kicks", 
      "Leaf", 
      "GT-R", 
      "370Z", 
      "Frontier", 
      "Titan", 
      "Juke", 
      "Qashqai", 
      "X-Trail", 
      "NV200", 
      "NV3500",
      "370Z Nismo",
      "GT-R Nismo",
      "Murano CrossCabriolet",
      "Rogue Sport",
      "Pathfinder Hybrid",
      "Altima Coupe",
      "Maxima Platinum",
      "Juke Nismo",
      "Kicks SR",
      "Leaf e+",
      "Titan XD",
      "Armada Platinum",
      "Frontier Crew Cab",
      "Xterra",
      "NV1500",
      "NV2500",
      "NV3500 HD",
      "Rogue Select",
      "Qashqai e-Power"
    ]
  },
  {
    brand: "Hyundai",
    models: [
      "Elantra", 
      "Sonata", 
      "Tucson", 
      "Santa Fe", 
      "Kona", 
      "Accent", 
      "Azera", 
      "Veloster", 
      "Ioniq", 
      "Palisade", 
      "Venue", 
      "Genesis", 
      "Equus", 
      "Creta", 
      "Nexo", 
      "Staria", 
      "Bayon", 
      "i10", 
      "i20", 
      "i30",
      "Tucson Hybrid",
      "Santa Cruz",
      "Kona Electric",
      "Ioniq 5",
      "Ioniq 6",
      "Veloster N",
      "Palisaade Calligraphy",
      "Sonata Hybrid",
      "Sonata Plug-in Hybrid",
      "Elantra Hybrid",
      "i30 N",
      "i40",
      "ix35",
      "Tucson Plug-in Hybrid",
      "Staria Lounge",
      "Creta Turbo",
      "Kona N"
    ]
  },
  {
    brand: "Kia",
    models: [
      "Rio", 
      "Forte", 
      "Optima", 
      "Sorento", 
      "Sportage", 
      "Stinger", 
      "Telluride", 
      "Soul", 
      "Seltos", 
      "Carnival", 
      "Cadenza", 
      "K900", 
      "Niro", 
      "Picanto", 
      "Cerato", 
      "Mohave", 
      "Sonet", 
      "Pegas", 
      "Stonic", 
      "XCeed",
      "K5",
      "K3",
      "K900",
      "Stinger GT",
      "Seltos Turbo",
      "Sportage Hybrid",
      "Sorento Hybrid",
      "Niro EV",
      "Soul EV",
      "Forte Koup",
      "Cadenza Limited",
      "Mohave Master",
      "Carens",
      "Venga",
      "Kia EV6",
      "Kia Ceed",
      "Kia XCeed",
      "Kia Niro Plug-in Hybrid"
    ]
  },
  {
    brand: "Mazda",
    models: [
      "Mazda3", 
      "Mazda6", 
      "CX-3", 
      "CX-5", 
      "MX-5", 
      "CX-30", 
      "CX-9", 
      "Mazda2", 
      "Mazda5", 
      "RX-8", 
      "RX-7", 
      "CX-7", 
      "MazdaSpeed3", 
      "MazdaSpeed6", 
      "B-Series", 
      "Tribute", 
      "MPV", 
      "Navajo", 
      "323", 
      "626",
      "Mazda MX-30",
      "Mazda CX-50",
      "Mazda CX-60",
      "Mazda CX-70",
      "Mazda 2 Hybrid",
      "Mazda 3 Turbo",
      "Mazda 6 Turbo",
      "Mazda RX-9",
      "Mazda 5",
      "Mazda 121",
      "Mazda 626 Coupe",
      "Mazda 929",
      "Mazda MPV",
      "Mazda CX-4",
      "Mazda CX-8",
      "Mazda 3 Sport",
      "Mazda 6 Atenza"
    ]
  },
  {
    brand: "Subaru",
    models: [
      "Impreza", 
      "Legacy", 
      "Outback", 
      "Forester", 
      "Crosstrek", 
      "WRX", 
      "BRZ", 
      "Ascent", 
      "Baja", 
      "Tribeca", 
      "SVX", 
      "Justy", 
      "Leone", 
      "Alcyone", 
      "Exiga", 
      "Sambar", 
      "Vivio", 
      "Rex", 
      "Pleo", 
      "Stella",
      "Evoltis",
      "Trezia",
      "Loyale",
      "DL",
      "XT",
      "Alcyone SVX",
      "Forester e-Boxer",
      "Outback Wilderness",
      "Crosstrek Hybrid",
      "Impreza WRX STI",
      "Legacy GT",
      "Forester Turbo",
      "Subaru 360",
      "Subaru R2",
      "Subaru Sambar Dias",
      "Subaru Pleo Plus",
      "Subaru R1",
      "Subaru R2",
      "Subaru Levorg",
      "Subaru WRX S4",
      "Subaru BRZ tS"
    ]
  },
  {
    brand: "Tesla",
    models: [
      "Model S", 
      "Model 3", 
      "Model X", 
      "Model Y", 
      "Roadster", 
      "Cybertruck", 
      "Semi", 
      "Model 2", 
      "Model R", 
      "Model C", 
      "Model P", 
      "Model T", 
      "Model A", 
      "Model B", 
      "Model Z", 
      "Model Q", 
      "Model V", 
      "Model W", 
      "Model E", 
      "Model F",
      "Model 1",
      "Model 4",
      "Model 5",
      "Model 6",
      "Model 7",
      "Model 8",
      "Model 9",
      "Model 10",
      "Model 11",
      "Model 12",
      "Model 13",
      "Model 14",
      "Model 15",
      "Model 16",
      "Model 17",
      "Model 18",
      "Model 19",
      "Model 20"
    ]
  },
  {
    brand: "Volvo",
    models: [
      "S60", 
      "S90", 
      "XC40", 
      "XC60", 
      "XC90", 
      "V40", 
      "V60", 
      "V90", 
      "C30", 
      "C70", 
      "S40", 
      "S80", 
      "V50", 
      "V70", 
      "XC70", 
      "850", 
      "940", 
      "960", 
      "240", 
      "740",
      "C70 Coupe",
      "C70 Convertible",
      "S70",
      "V70 II",
      "S80 II",
      "S90 II",
      "V40 II",
      "XC60 II",
      "XC90 II",
      "V60 II",
      "S60 II",
      "S40 II",
      "V50 II",
      "V90 II",
      "S60 Cross Country",
      "V60 Cross Country",
      "XC40 Recharge",
      "XC60 Recharge",
      "XC90 Recharge",
      "S60 Recharge",
      "V60 Recharge"
    ]
  },
  {
    brand: "Jaguar",
    models: [
      "XE", 
      "XF", 
      "XJ", 
      "F-Pace", 
      "E-Pace", 
      "I-Pace", 
      "F-Type", 
      "XK", 
      "X-Type", 
      "S-Type", 
      "XJ220", 
      "XJR", 
      "XFR", 
      "XKR", 
      "XK8", 
      "XJ8", 
      "XJ6", 
      "XJ12", 
      "XJ-S", 
      "XJ40",
      "C-X75",
      "C-X16",
      "XJ40",
      "XJ-SC",
      "XJ12C",
      "XJ12L",
      "XK120",
      "XK140",
      "XK150",
      "XK8",
      "F-Type R",
      "F-Type SVR",
      "F-Type P300",
      "F-Type P450",
      "F-Type P575",
      "I-Pace EV320",
      "I-Pace EV400",
      "F-Pace SVR",
      "E-Pace R-Dynamic",
      "XJ50",
      "XJ6C",
      "XJ8L",
      "XJ8C"
    ]
  },
  {
    brand: "Land Rover",
    models: [
      "Range Rover", 
      "Discovery", 
      "Defender", 
      "Evoque", 
      "Velar", 
      "Freelander", 
      "Range Rover Sport", 
      "Range Rover Velar", 
      "Range Rover Evoque", 
      "Discovery Sport", 
      "Defender 90", 
      "Defender 110", 
      "Defender 130", 
      "Range Rover Classic", 
      "Range Rover P38", 
      "Range Rover L322", 
      "Range Rover L405", 
      "Range Rover L460", 
      "Discovery Series I", 
      "Discovery Series II",
      "Range Rover SVAutobiography",
      "Defender 110 V8",
      "Defender 130",
      "Discovery 5",
      "Range Rover Sport SVR",
      "Range Rover Velar SVAutobiography",
      "Evoque Convertible",
      "Freelander 2",
      "Defender 90 V8",
      "Range Rover Evoque P300e",
      "Discovery 4",
      "Range Rover L405 PHEV",
      "Defender 75th Anniversary Edition",
      "Range Rover Sport HST",
      "Discovery Sport PHEV"
    ]
  },
  {
    brand: "Porsche",
    models: [
      "911", 
      "Cayenne", 
      "Macan", 
      "Panamera", 
      "Taycan", 
      "Boxster", 
      "Cayman", 
      "Carrera GT", 
      "918 Spyder", 
      "356", 
      "944", 
      "928", 
      "968", 
      "959", 
      "924", 
      "718", 
      "550 Spyder", 
      "Carrera", 
      "Targa", 
      "Turbo",
      "718 Spyder",
      "911 Turbo S",
      "911 GT3",
      "911 GT2 RS",
      "Cayenne Coupe",
      "Macan S",
      "Panamera Turbo",
      "Taycan 4S",
      "Taycan Turbo",
      "Taycan Turbo S",
      "Boxster Spyder",
      "Cayman GT4",
      "911 R",
      "911 Speedster",
      "911 Carrera 4",
      "911 Carrera 4S",
      "911 Carrera S",
      "911 Carrera 2",
      "911 Carrera 2S",
      "911 Targa 4",
      "911 Targa 4S"
    ]
  },
  {
    brand: "Ferrari",
    models: [
      "488", 
      "Portofino", 
      "Roma", 
      "F8", 
      "SF90", 
      "California", 
      "LaFerrari", 
      "Enzo", 
      "F12", 
      "812 Superfast", 
      "GTC4Lusso", 
      "Monza SP1", 
      "Monza SP2", 
      "F40", 
      "F50", 
      "Testarossa", 
      "Dino", 
      "250 GTO", 
      "330 P4", 
      "365 GTB/4", 
      "456 GT", 
      "550 Maranello", 
      "575M Maranello", 
      "599 GTB Fiorano", 
      "612 Scaglietti",
      "F8 Tributo",
      "F8 Spider",
      "488 Pista",
      "488 Pista Spider",
      "SF90 Stradale",
      "SF90 Spider",
      "Roma Spider",
      "FXX-K",
      "FXX-K Evo",
      "SP1",
      "SP2",
      "F40 Competizione",
      "F50 GT",
      "P80/C",
      "FXX",
      "F430",
      "458 Italia",
      "458 Spider",
      "488 GTB",
      "California T",
      "Dino 246",
      "Dino 308 GT4",
      "F12tdf",
      "812 GTS",
      "Monza SP3"
    ]
  },
  {
    brand: "Lamborghini",
    models: [
      "Huracan", 
      "Aventador", 
      "Urus", 
      "Gallardo", 
      "Murcielago", 
      "Diablo", 
      "Countach", 
      "Reventon", 
      "Veneno", 
      "Sesto Elemento", 
      "Centenario", 
      "Miura", 
      "Espada", 
      "Islero", 
      "Jarama", 
      "LM002", 
      "Silhouette", 
      "Jalpa", 
      "350 GT", 
      "400 GT", 
      "Egoista", 
      "Estoque", 
      "Asterion", 
      "SC18 Alston",
      "Gallardo Spyder",
      "Aventador SV",
      "Aventador SVJ",
      "Huracan Performante",
      "Huracan Spyder",
      "Huracan EVO",
      "Urus Performante",
      "Sian",
      "Reventon Roadster",
      "Countach LPI 800-4",
      "Miura SV",
      "Diablo SV",
      "Murcielago LP 640",
      "Gallardo Superleggera",
      "Aventador J",
      "Huracan STO"
    ]
  }
];
