/** @format */

export const recommandationsGenerale = [
  [
    {
      id: "1",
      title: "Ford Mustang GT 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Ford",
      model: "Mustang",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-12-15 23:59:59",
      premiumExpiration: "2024-10-30 23:59:59",
    },
    {
      id: "2",
      title: "Honda CB 2019",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: "1",
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "Honda",
      model: "CB",
      year: "2019",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto fiable et économique, parfaite pour les trajets quotidiens.",
      fuelType: "Essence",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2024-11-30 23:59:59",
    },
    {
      id: "3",
      title: "Yamaha MT-07 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: "1",
      condition: "Occasion",
      price: "60",
      city: "Corte, 20250",
      mark: "Yamaha",
      model: "MT-07",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "3 000",
      phoneNumber: "0780853615",
      description:
        "Une moto sportive avec une excellente maniabilité et des performances impressionnantes.",
      fuelType: "Essence",
      premium: false,
      annonceState: "loué",
      expirationDate: "2025-01-10 23:59:59",
    },
    {
      id: "4",
      title: "Tesla Model S 2022",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "2",
      condition: "Neuf",
      price: "80 000",
      city: "Corte, 20250",
      mark: "Tesla",
      model: "Model S",
      year: "2022",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853616",
      description:
        "Une voiture électrique de luxe avec une autonomie exceptionnelle et des technologies de pointe.",
      fuelType: "Électrique",
      premium: true,
      annonceState: "vendu",
      expirationDate: "2024-12-22 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
  ],
  [
    {
      id: "5",
      title: "BMW X5 2021",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "3",
      condition: "Neuf",
      price: "70 000",
      city: "Corte, 20250",
      mark: "BMW",
      model: "X5",
      year: "2021",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853617",
      description:
        "Un SUV de luxe avec un intérieur spacieux et des performances puissantes.",
      fuelType: "Diesel",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-11-25 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "6",
      title: "Kawasaki Ninja 2018",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: "1",
      condition: "Occasion",
      price: "45",
      city: "Corte, 20250",
      mark: "Kawasaki",
      model: "Ninja",
      year: "2018",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "7 000",
      phoneNumber: "0780853618",
      description:
        "Une moto sportive avec un design agressif et des performances de pointe.",
      fuelType: "Essence",
      premium: false,
      annonceState: "loué",
      expirationDate: "2025-01-05 23:59:59",
    },
    {
      id: "7",
      title: "Audi A4 2020",
      images: [
        require("../assets/ford5.jpeg"),
        require("..//assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "5",
      condition: "Neuf",
      price: "50 000",
      city: "Corte, 20250",
      mark: "Audi",
      model: "A4",
      year: "2020",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853619",
      description:
        "Une berline de luxe avec un intérieur raffiné et des technologies avancées.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-12-01 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "8",
      title: "Harley-Davidson Sportster 2017",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: "1",
      condition: "Occasion",
      price: "55",
      city: "Corte, 20250",
      mark: "Harley-Davidson",
      model: "Sportster",
      year: "2017",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "8 000",
      phoneNumber: "0780853620",
      description:
        "Une moto emblématique avec un style classique et des performances robustes.",
      fuelType: "Essence",
      premium: false,
      annonceState: "loué",
      expirationDate: "2024-12-20 23:59:59",
    },
  ],
  [
    {
      id: "9",
      title: "Mercedes-Benz GLE 2021",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "2",
      condition: "Neuf",
      price: "75 000",
      city: "Corte, 20250",
      mark: "Mercedes-Benz",
      model: "GLE",
      year: "2021",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853621",
      description:
        "Un SUV de luxe avec un intérieur spacieux et des technologies de pointe.",
      fuelType: "Diesel",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-11-28 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "10",
      title: "Ducati Monster 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: "1",
      condition: "Occasion",
      price: "65",
      city: "Corte, 20250",
      mark: "Ducati",
      model: "Monster",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "4 000",
      phoneNumber: "0780853622",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "loué",
      expirationDate: "2025-01-15 23:59:59",
    },
  ],
];

export const voitures = [
  [
    {
      id: "1",
      title: "BMW Série 3 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("..//assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "BMW",
      model: "Série 3",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-12-15 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "2",
      title: "Audi A4 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Audi",
      model: "A4",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2024-11-30 23:59:59",
    },
    {
      id: "3",
      title: "Mercedes-Benz Classe C 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Mercedes-Benz",
      model: "Classe C",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2025-01-10 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "4",
      title: "Tesla Model 3 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Tesla",
      model: "Model 3",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Électrique",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2024-12-22 23:59:59",
    },
  ],
  [
    {
      id: "5",
      title: "Porsche 911 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Porsche",
      model: "911",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "vendu",
      expirationDate: "2024-11-25 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "6",
      title: "Lexus IS 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Lexus",
      model: "IS",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2025-01-05 23:59:59",
    },
    {
      id: "7",
      title: "Jaguar XE 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Jaguar",
      model: "XE",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-12-01 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "8",
      title: "Chevrolet Camaro 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("..//assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Chevrolet",
      model: "Camaro",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "vendu",
      expirationDate: "2024-12-20 23:59:59",
    },
  ],
  [
    {
      id: "9",
      title: "Nissan Altima 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Nissan",
      model: "Altima",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "vendu",
      expirationDate: "2024-11-28 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "10",
      title: "Subaru Impreza 2024",
      images: [
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
        require("../assets/ford5.jpeg"),
      ],
      type: "Voiture",
      transaction: "Vente",
      quantity: "4",
      condition: "Neuf",
      price: "55 000",
      city: "Corte, 20250",
      mark: "Subaru",
      model: "Impreza",
      year: "2024",
      gearbox: "Automatique",
      climatisation: "Très bonne état",
      klm_counter: "0",
      phoneNumber: "0780853613",
      description:
        "Une voiture sportive emblématique avec un design élégant et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2025-01-15 23:59:59",
    },
  ],
];

export const motos = [
  [
    {
      id: "1",
      title: "Kawasaki Ninja 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: "1",
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "Kawasaki",
      model: "Ninja",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "loué",
      expirationDate: "2024-12-15 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: "2",
      title: "Yamaha YZF-R3 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: "1",
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "Yamaha",
      model: "YZF-R3",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "loué",
      expirationDate: "2024-11-30 23:59:59",
    },
    {
      id: 3,
      title: "Suzuki GSX-R600 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "Suzuki",
      model: "GSX-R600",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "loué",
      expirationDate: "2025-01-10 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: 4,
      title: "KTM RC 390 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "KTM",
      model: "RC 390",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "loué",
      expirationDate: "2024-12-22 23:59:59",
    },
  ],
  [
    {
      id: 5,
      title: "Ducati Panigale V2 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "Ducati",
      model: "Panigale V2",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-11-25 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: 6,
      title: "BMW S1000RR 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "BMW",
      model: "S1000RR",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2024-11-25 23:59:59",
    },
    {
      id: 7,
      title: "Triumph Street Triple 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, 20250",
      mark: "Triumph",
      model: "Street Triple",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto sportive avec un design unique et des performances exceptionnelles.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-11-25 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
    {
      id: 8,
      title: "Harley-Davidson Sportster 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, Corse",
      mark: "Harley-Davidson",
      model: "Sportster",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto fiable et économique, parfaite pour les trajets quotidiens.",
      fuelType: "Essence",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2024-11-25 23:59:59",
    },
  ],
  [
    {
      id: 9,
      title: "KTM 390 Duke 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, Corse",
      mark: "KTM",
      model: "390 Duke",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto fiable et économique, parfaite pour les trajets quotidiens.",
      fuelType: "Essence",
      premium: true,
      annonceState: "disponible",
      expirationDate: "2024-11-25 23:59:59",
      premiumExpiration: "2024-10-30 23:59:59",
    },
    {
      id: 10,
      title: "Honda CBR500R 2020",
      images: [
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
        require("../assets/motoHarley.png"),
      ],
      type: "Moto",
      transaction: "Location",
      quantity: 1,
      condition: "Occasion",
      price: "50",
      city: "Corte, Corse",
      mark: "Honda",
      model: "CBR500R",
      year: "2020",
      gearbox: "Manuel",
      climatisation: "Non applicable",
      klm_counter: "5 000",
      phoneNumber: "0780853614",
      description:
        "Une moto fiable et économique, parfaite pour les trajets quotidiens.",
      fuelType: "Essence",
      premium: false,
      annonceState: "disponible",
      expirationDate: "2024-11-25 23:59:59",
      premiumExpiration: "2024-10-22 23:59:59",
    },
  ],
];
