export const motoBrandsAndModels = [
  {
    brand: "Harley-Davidson",
    models: [
      "Sportster", 
      "Softail", 
      "Touring", 
      "Street", 
      "CVO", 
      "Trike", 
      "LiveWire", 
      "Dyna", 
      "V-Rod", 
      "Road King",
      "Fat Boy",
      "Street Glide",
      "Road Glide",
      "Iron 883",
      "Forty-Eight",
      "Breakout",
      "Fat Bob",
      "Heritage Classic",
      "Low Rider",
      "Street Bob",
      "Pan America",
      "Roadster",
      "SuperLow",
      "Nightster",
      "Fat Boy Special",
      "Street 500",
      "Street 750",
      "Electra Glide",
      "Ultra Limited",
      "Road King Special",
      "CVO Street Glide",
      "CVO Road Glide",
      "CVO Limited",
      "CVO Tri Glide",
      "LiveWire One",
      "Pan America 1250 Special",
      "Sport Glide",
      "Low Rider S",
      "Softail Standard",
      "Breakout 114",
      "Fat Bob 114"
    ]
  },
  {
    brand: "Honda",
    models: [
      "CBR1000RR", 
      "Gold Wing", 
      "Africa Twin", 
      "CBR600RR", 
      "Rebel 500", 
      "Shadow Phantom", 
      "CRF450R", 
      "CB500F", 
      "CB650R", 
      "CB300R",
      "VFR800", 
      "CBR500R", 
      "CT125", 
      "XR650L", 
      "CB125R", 
      "Grom", 
      "CBR250R", 
      "NC750X", 
      "VFR1200F", 
      "Fury",
      "CBR150R",
      "CBR250RR",
      "CBR300R",
      "CBR650F",
      "CBR1000RR-R Fireblade",
      "CB500X",
      "CRF1000L Africa Twin",
      "CRF250L",
      "CRF110F",
      "CRF125F",
      "CBR600F",
      "CBR900RR",
      "VFR1200X",
      "CBR650R",
      "CBR500R",
      "CBR1000RR SP",
      "CBR1000RR SP2"
    ]
  },
  {
    brand: "Yamaha",
    models: [
      "YZF-R1", 
      "MT-07", 
      "MT-09", 
      "Tracer 900", 
      "XSR900", 
      "FJR1300", 
      "Tenere 700", 
      "Bolt", 
      "V Star 250", 
      "WR250R",
      "FZ-09",
      "R6",
      "R3",
      "FZ-07",
      "MT-10",
      "Niken",
      "TMAX",
      "XT1200Z Super Ténéré",
      "YZF-R3",
      "YZF-R125",
      "YZF-R6",
      "MT-03",
      "FZ-10",
      "Ténéré 1200",
      "XSR700",
      "XSR900 Abarth",
      "FZ6",
      "FZ1",
      "YZF-R125",
      "YZF-R15",
      "YZF-R3",
      "NMAX 125",
      "XMAX 300",
      "TMAX 560",
      "MT-125",
      "MT-15",
      "MT-25",
      "MT-03",
      "FJR1300AE",
      "FJR1300AS"
    ]
  },
  {
    brand: "Kawasaki",
    models: [
      "Ninja H2", 
      "Ninja ZX-10R", 
      "Ninja 400", 
      "Z900", 
      "Z650", 
      "Versys 650", 
      "Vulcan S", 
      "KX450F", 
      "KLX250", 
      "Ninja 250", 
      "Ninja 300", 
      "Z1000", 
      "Concours 14", 
      "W800", 
      "Ninja ZX-6R", 
      "KX250", 
      "Ninja 1000", 
      "Vulcan 900", 
      "Z125 Pro", 
      "KX85",
      "Ninja 650",
      "Z400",
      "Versys 1000",
      "Vulcan 1700",
      "Ninja ZX-14R",
      "KX450",
      "KLX300",
      "Ninja 125",
      "Ninja 300 ABS",
      "Ninja 400 ABS",
      "Z125",
      "Z800",
      "Z1000SX",
      "Ninja H2R",
      "Ninja 1000SX"
    ]
  },
  {
    brand: "Suzuki",
    models: [
      "GSX-R1000", 
      "Hayabusa", 
      "V-Strom 650", 
      "SV650", 
      "DR-Z400SM", 
      "Boulevard M109R", 
      "GSX-S750", 
      "Burgman 400", 
      "RM-Z450", 
      "Katana",
      "GSX-R750",
      "GSX-R600",
      "SV1000",
      "V-Strom 1000",
      "Intruder M1800R",
      "Burgman 650",
      "GSX-S1000",
      "DL650 V-Strom",
      "GSX-R125",
      "GSR750",
      "SV650X",
      "GSX-S1000GT",
      "V-Strom 1050",
      "SV650S",
      "GSX-R1100",
      "GSX-R1300 Hayabusa",
      "Burgman 200",
      "Burgman 125",
      "DR-Z400S",
      "DR-Z125L",
      "GSX-R150",
      "GSX-S125",
      "V-Strom 250",
      "SV400",
      "Intruder 1500",
      "GSX-S750Z",
      "GSX-R600K",
      "GSX-R750L"
    ]
  },
  {
    brand: "Ducati",
    models: [
      "Panigale V4", 
      "Monster", 
      "Multistrada", 
      "Scrambler", 
      "Diavel", 
      "Hypermotard", 
      "SuperSport", 
      "Streetfighter", 
      "XDiavel", 
      "DesertX", 
      "Ducati 1098", 
      "Ducati 1199 Panigale", 
      "Ducati 848", 
      "Ducati Diavel 1260", 
      "Ducati Scrambler Icon", 
      "Ducati Panigale V2", 
      "Ducati Monster 1200", 
      "Ducati Multistrada 1260", 
      "Ducati Streetfighter V4", 
      "Ducati Superleggera V4", 
      "Ducati Panigale R",
      "Ducati 748",
      "Ducati 996",
      "Ducati 999",
      "Ducati 1098R",
      "Ducati 1198",
      "Ducati 1299 Panigale",
      "Ducati Streetfighter 848",
      "Ducati Scrambler 1100",
      "Ducati Multistrada 950",
      "Ducati Panigale V4 S",
      "Ducati Panigale V4 R",
      "Ducati Diavel 1260 S",
      "Ducati Monster 821",
      "Ducati Monster 797",
      "Ducati Hypermotard 950",
      "Ducati Hypermotard 950 SP"
    ]
  },
  {
    brand: "BMW",
    models: [
      "S1000RR", 
      "R1250GS", 
      "F850GS", 
      "R nineT", 
      "K1600GTL", 
      "G310R", 
      "F900R", 
      "R1250RT", 
      "F750GS", 
      "C400X",
      "R1200GS",
      "S1000R",
      "K1600B",
      "F800GS",
      "R1250R",
      "G310GS",
      "K1600GT",
      "R nineT Scrambler",
      "R nineT Pure",
      "F800R",
      "S1000XR",
      "R1250R Rallye",
      "F850GS Adventure",
      "K1200LT",
      "K1300S",
      "R1200R",
      "R1200RT",
      "R1250GS Adventure",
      "S1000RR M",
      "F900XR",
      "G310GS Adventure",
      "R nineT Urban G/S",
      "R nineT Racer",
      "R nineT 100 Years",
      "K1600 Grand America",
      "K1600 GTL Exclusive"
    ]
  },
  {
    brand: "Triumph",
    models: [
      "Bonneville", 
      "Street Triple", 
      "Tiger 900", 
      "Rocket 3", 
      "Speed Triple", 
      "Thruxton", 
      "Scrambler 1200", 
      "Daytona Moto2", 
      "Tiger 1200", 
      "Trident 660", 
      "Tiger 800", 
      "Bonneville T120", 
      "Street Twin", 
      "Speedmaster", 
      "Bobber", 
      "Tiger 1050", 
      "Sprint GT", 
      "Daytona 675", 
      "Trophy", 
      "Rocket 3 R", 
      "Street Triple RS",
      "Tiger 850 Sport",
      "Bonneville Bobber Black",
      "Street Scrambler",
      "Tiger 900 Rally",
      "Speed Triple 1200 RS",
      "Thruxton RS",
      "Rocket 3 GT",
      "Tiger 1200 Rally Pro",
      "Street Triple R",
      "Daytona 955i",
      "Sprint 1050",
      "Tiger 1050 Sport",
      "Bonneville Speedmaster",
      "Tiger 800 XCA",
      "Street Triple 765",
      "Tiger 900 GT",
      "Thruxton 1200",
      "Rocket 3 R 221"
    ]
  },
  {
    brand: "KTM",
    models: [
      "Duke 390", 
      "1290 Super Duke R", 
      "790 Adventure", 
      "450 SX-F", 
      "250 EXC-F", 
      "RC 390", 
      "690 Enduro R", 
      "890 Duke R", 
      "500 EXC-F", 
      "Freeride E-XC",
      "390 Duke",
      "1190 Adventure",
      "1290 Super Adventure",
      "250 Duke",
      "350 EXC-F",
      "690 SMC R",
      "890 Adventure",
      "950 Adventure",
      "125 Duke",
      "300 EXC",
      "390 Adventure",
      "890 R",
      "450 EXC",
      "500 EXC",
      "250 SX",
      "350 SX-F",
      "300 XC-W",
      "250 XC-F",
      "690 Duke",
      "1290 Super Adventure S",
      "1290 Super Adventure R",
      "390 Duke R",
      "250 EXC",
      "350 EXC",
      "690 Enduro",
      "890 SMT",
      "1290 Super Duke GT"
    ]
  },
  {
    brand: "Indian",
    models: [
      "Scout", 
      "Chief", 
      "Chieftain", 
      "Roadmaster", 
      "FTR", 
      "Springfield", 
      "Vintage", 
      "Dark Horse", 
      "Challenger", 
      "Super Chief", 
      "Indian Chief Dark Horse", 
      "Indian Scout Bobber", 
      "Indian FTR 1200", 
      "Indian Roadmaster Limited", 
      "Indian Chieftain Limited", 
      "Indian Super Chief Limited", 
      "Indian Vintage Dark Horse", 
      "Indian Scout Sixty", 
      "Indian Chief Classic", 
      "Indian Chieftain Classic",
      "Indian Chief Vintage",
      "Indian Super Chief Classic",
      "Indian Roadmaster Classic",
      "Indian Scout 100th Anniversary",
      "Indian FTR Rally",
      "Indian FTR 1200 S",
      "Indian Chieftain Dark Horse",
      "Indian Challenger Dark Horse",
      "Indian Vintage",
      "Indian Bobber",
      "Indian Scout Bobber Twenty",
      "Indian Roadmaster Elite",
      "Indian Chieftain Elite",
      "Indian Springfield Dark Horse",
      "Indian Scout Sixty ABS",
      "Indian FTR 1200 Race Replica"
    ]
  },
  {
    brand: "Aprilia",
    models: [
      "RSV4", 
      "Tuono V4", 
      "RS 660", 
      "Tuareg 660", 
      "Shiver 900", 
      "Dorsoduro 900", 
      "Caponord 1200", 
      "Mana 850", 
      "SRV 850", 
      "Pegaso 650",
      "RS 125",
      "RS 250",
      "Tuono 125",
      "Dorsoduro 750",
      "CapoNord 1000",
      "Mille",
      "Futura",
      "Sportcity 250",
      "Scarabeo 500",
      "Leonardo 125",
      "Mojito 50",
      "RS 50",
      "RS 125 GP",
      "Tuono 660",
      "Dorsoduro 900 Factory",
      "Shiver 750",
      "Mille GT",
      "Futura 1000",
      "Sportcity 300",
      "Scarabeo 200",
      "Leonardo 150",
      "Mojito 125",
      "Caponord 1200 Rally",
      "Tuareg 125",
      "RS 250 GP",
      "Dorsoduro 1200",
      "RSV4 Factory",
      "RSV4 RF",
      "Tuono V4 1100",
      "Tuono V4 Factory",
      "RS 660 Factory"
    ]
  },
  {
    brand: "Moto Guzzi",
    models: [
      "V7 III", 
      "California Touring", 
      "California 1400", 
      "Eldorado", 
      "Audace", 
      "MGX-21", 
      "Griso 1200", 
      "Norge 1200", 
      "Stelvio 1200", 
      "Le Mans 850", 
      "V9 Bobber", 
      "V9 Roamer", 
      "Bellagio", 
      "Breva 1100", 
      "Nevada 750", 
      "Faro 750", 
      "Galletto", 
      "Dingo", 
      "Lario", 
      "Cylindro",
      "V7 Stone",
      "V7 Special",
      "V7 Racer",
      "V85 TT",
      "California 1400 Touring",
      "California 1400 Custom",
      "Griso 8V",
      "Griso 1200 SE",
      "Stelvio 1200 NTX",
      "Norge GT",
      "Audace Carbon",
      "MGX-21 Flying Fortress",
      "Bellagio 940",
      "Breva 750",
      "Nevada Classic",
      "Faro 500",
      "Dingo 125",
      "Lario 650",
      "Cylindro 500"
    ]
  },
  {
    brand: "Royal Enfield",
    models: [
      "Classic 350", 
      "Bullet 500", 
      "Himalayan", 
      "Interceptor 650", 
      "Continental GT 650", 
      "Meteor 350", 
      "Thunderbird X", 
      "Scram 411", 
      "Electra 350", 
      "Classic 500",
      "Himalayan 411", 
      "Bullet 350", 
      "Interceptor 650 GT", 
      "Continental GT 535", 
      "Thunderbird 500", 
      "Classic 500 Pegasus", 
      "Meteor 650", 
      "Himalayan 650", 
      "Bullet Trials", 
      "Classic 350 Signals", 
      "Interceptor 650 Chrome",
      "Classic 500 EFI",
      "Himalayan 400",
      "Bullet 350 X",
      "Interceptor 650 Stealth Black",
      "Continental GT 650 Mark II",
      "Meteor 350 Fireball",
      "Thunderbird X 500",
      "Classic 350 Redditch",
      "Himalayan 650 Adventure",
      "Bullet 500 Trials",
      "Interceptor 650 Chrome Edition",
      "Continental GT 650 Black Magic",
      "Meteor 350 Supernova",
      "Classic 350 Dark",
      "Himalayan 450",
      "Bullet 350 X Classic"
    ]
  },
  {
    brand: "Husqvarna",
    models: [
      "Vitpilen 401", 
      "Svartpilen 401", 
      "701 Enduro", 
      "701 Supermoto", 
      "FE 501", 
      "TE 300i", 
      "FC 450", 
      "TX 300i", 
      "FE 350", 
      "TE 150i", 
      "Nuda 900", 
      "701 Vitpilen", 
      "701 Svartpilen", 
      "Husqvarna 125", 
      "Husqvarna 250", 
      "Husqvarna 501", 
      "Husqvarna 701", 
      "Husqvarna 350", 
      "Husqvarna 450", 
      "Husqvarna 701 Supermoto", 
      "Husqvarna 701 Enduro",
      "Husqvarna 501 FE",
      "Husqvarna 701 LR",
      "Husqvarna 250 TE",
      "Husqvarna 450 TE",
      "Husqvarna 701 Supermoto R",
      "Husqvarna 125 WR",
      "Husqvarna 250 WR",
      "Husqvarna 350 FE",
      "Husqvarna 450 FE",
      "Husqvarna 701 Enduro R",
      "Husqvarna 701 Vitpilen 701",
      "Husqvarna 701 Svartpilen 701",
      "Husqvarna 250 FC",
      "Husqvarna 350 FC",
      "Husqvarna 450 FC"
    ]
  },
  {
    brand: "MV Agusta",
    models: [
      "Brutale 800", 
      "F3 800", 
      "Dragster 800", 
      "Turismo Veloce 800", 
      "Superveloce 800", 
      "F4", 
      "Rivale 800", 
      "Stradale 800", 
      "Brutale 1000", 
      "Rush 1000", 
      "F3 675", 
      "Brutale 910", 
      "F4 1000", 
      "F4 RC", 
      "Brutale 800 RR", 
      "Dragster 800 RR", 
      "Turismo Veloce 800 Lusso", 
      "Superveloce 75 Anniversario", 
      "F4 Senna", 
      "Brutale 1000 Serie Oro", 
      "F3 800 RC",
      "Brutale 1000 RR",
      "F4 1078",
      "F3 675 RC",
      "Brutale 910 R",
      "Dragster 1000",
      "Superveloce 800 Serie Oro",
      "F4 750",
      "F3 800 Ago",
      "Brutale 800 America",
      "Rivale 800 EAS",
      "Turismo Veloce 800 RC",
      "F4 1000 R",
      "Brutale 800 2019",
      "F3 800 2019"
    ]
  },
  {
    brand: "Benelli",
    models: [
      "TNT 600", 
      "Leoncino 500", 
      "TRK 502", 
      "Imperiale 400", 
      "TNT 899", 
      "TNT 1130", 
      "302R", 
      "302S", 
      "TRK 251", 
      "TNT 135", 
      "BN 125", 
      "Tornado 1130", 
      "Zafferano 250", 
      "Cafè Racer 752", 
      "Leonardo 150", 
      "TNT 750", 
      "TNT 600i", 
      "TNT 125", 
      "TRK 800", 
      "TNT 600 Sport", 
      "TNT 899 Sport",
      "Benelli 502C",
      "Benelli Leoncino 250",
      "Benelli TRK 502 X",
      "Benelli 752S",
      "Benelli Tornado 650",
      "Benelli TRK 800",
      "Benelli BN 251",
      "Benelli Caffè Nero",
      "Benelli 125",
      "Benelli 250",
      "Benelli 300",
      "Benelli 600",
      "Benelli 750",
      "Benelli 900"
    ]
  },
  {
    brand: "Bajaj",
    models: [
      "Pulsar 150", 
      "Pulsar NS200", 
      "Pulsar RS200", 
      "Dominar 400", 
      "Avenger 220", 
      "CT 100", 
      "Platina 110", 
      "Discover 125", 
      "Pulsar 180", 
      "Pulsar 220F", 
      "V15", 
      "Chetak", 
      "Pulsar 200", 
      "Pulsar 135", 
      "Pulsar 250", 
      "Ninja 300", 
      "Avenger Cruise 220", 
      "Avenger Street 220", 
      "Bajaj Qute", 
      "Bajaj Dominar 250",
      "Pulsar 125",
      "Pulsar 180F",
      "Pulsar 220",
      "Pulsar 250F",
      "Pulsar 400",
      "Bajaj Avenger 180",
      "Bajaj Avenger 150",
      "Bajaj Discover 150",
      "Bajaj Discover 125 ST",
      "Bajaj Platina 100",
      "Bajaj Platina 110 H",
      "Bajaj CT 110",
      "Bajaj CT 125",
      "Bajaj Pulsar N160",
      "Bajaj Pulsar F250",
      "Bajaj Dominar 400 X",
      "Bajaj Dominar 250 X"
    ]
  },
  {
    brand: "Hero",
    models: [
      "Splendor Plus", 
      "HF Deluxe", 
      "Glamour", 
      "XPulse 200", 
      "Xtreme 160R", 
      "Passion Pro", 
      "Maestro Edge", 
      "Destini 125", 
      "Pleasure Plus", 
      "Super Splendor", 
      "Hero Xtreme 200R", 
      "Hero Glamour Xtec", 
      "Hero Hunk", 
      "Hero Karizma ZMR", 
      "Hero Achiever", 
      "Hero Impulse", 
      "Hero Passion XPro", 
      "Hero Maestro", 
      "Hero Xpulse 200T", 
      "Hero Super Splendor Xtec", 
      "Hero Xtreme 160R Stealth",
      "Hero Xtreme 200S",
      "Hero Xpulse 300",
      "Hero Glamour 125",
      "Hero Passion Pro 110",
      "Hero Maestro Edge 125",
      "Hero Destini 200",
      "Hero Xtreme 150",
      "Hero Hunk 150",
      "Hero Achiever 150",
      "Hero Super Splendor 125",
      "Hero Pleasure 110",
      "Hero Xtreme 180",
      "Hero Xpulse 200T Rally",
      "Hero Maestro Edge 110",
      "Hero Passion XPro 110"
    ]
  },
  {
    brand: "TVS",
    models: [
      "Apache RTR 160", 
      "Jupiter", 
      "Ntorq 125", 
      "Apache RR 310", 
      "Scooty Pep Plus", 
      "Apache RTR 200", 
      "Apache RTR 180", 
      "Star City", 
      "Victor", 
      "Radeon", 
      "XL100", 
      "Sport", 
      "Ntorq 125 Race Edition", 
      "Jupiter Classic", 
      "Jupiter 125", 
      "Apache RR 310 Race", 
      "Apache RTR 160 4V", 
      "Apache RTR 180 4V", 
      "TVS XL100 Heavy Duty", 
      "TVS Radeon Special Edition", 
      "TVS Scooty Zest",
      "Apache RTR 200 4V",
      "Apache RTR 310",
      "Jupiter 125 BS6",
      "Ntorq 125 Race",
      "Apache RR 310 BS6",
      "TVS iQube",
      "TVS Zest",
      "TVS Wego",
      "TVS Apache RTR 180 Race Edition",
      "TVS Apache RTR 160 2V",
      "TVS Radeon",
      "TVS XL100",
      "TVS Scooty Teenz",
      "TVS Jupiter Grande",
      "TVS Apache RTR 160 4V Race Edition"
    ]
  },
  {
    brand: "Piaggio",
    models: [
      "Vespa GTS", 
      "Vespa Primavera", 
      "Vespa Sprint", 
      "Liberty 150", 
      "Fly 150", 
      "MP3 500", 
      "BV 350", 
      "Typhoon 125", 
      "Medley 150", 
      "Zip 50",
      "Vespa 946",
      "Vespa PX",
      "Vespa S",
      "Vespa Elettrica",
      "Vespa 125",
      "Vespa 150",
      "Vespa 300",
      "Vespa Sei Giorni",
      "Vespa Touring",
      "Vespa Primavera 50",
      "Vespa 50",
      "Vespa 70",
      "Vespa 80",
      "Vespa 90",
      "Vespa 150 Super",
      "Vespa 180",
      "Vespa 200",
      "Vespa 300 HPE",
      "Vespa GTV",
      "Vespa 946 Emporio Armani",
      "Vespa Elettrica 70 km/h",
      "Vespa Elettrica 45 km/h",
      "Vespa Primavera 125",
      "Vespa Sprint 125",
      "Vespa GTS Super",
      "Vespa GTS 300",
      "Vespa GTS 125",
      "Vespa GTS Touring",
      "Vespa GTS Super Tech"
    ]
  }
];
