export const interactions = [
  {
    interactionId: 1,
    interactionType: "search",
    content: "Voiture rouge en excellent état",
    annonceId: 1,
    userId: 101,
    createdAt: new Date("2023-10-01T10:00:00Z"),
  },
  {
    interactionId: 2,
    interactionType: "search",
    content: "Moto Davidson à vendre",
    annonceId: 2,
    userId: 102,
    createdAt: new Date("2023-10-02T11:30:00Z"),
  },
  {
    interactionId: 3,
    interactionType: "search",
    content: "Recherche SUV avec faible kilométrage",
    annonceId: 1,
    userId: 103,
    createdAt: new Date("2023-10-03T12:45:00Z"),
  },
  {
    interactionId: 4,
    interactionType: "search",
    content: "Scooter électrique pas cher",
    annonceId: 2,
    userId: 104,
    createdAt: new Date("2023-10-04T14:15:00Z"),
  },
  {
    interactionId: 5,
    interactionType: "search",
    content: "Berline familiale avec GPS",
    annonceId: 3,
    userId: 105,
    createdAt: new Date("2023-10-05T09:00:00Z"),
  },
  {
    interactionId: 6,
    interactionType: "search",
    content: "Cabriolet avec toit ouvrant",
    annonceId: 1,
    userId: 106,
    createdAt: new Date("2023-10-06T08:00:00Z"),
  },
  {
    interactionId: 7,
    interactionType: "search",
    content: "Véhicule tout terrain à bon prix",
    annonceId: 3,
    userId: 107,
    createdAt: new Date("2023-10-07T15:30:00Z"),
  },
  {
    interactionId: 8,
    interactionType: "search",
    content: "Annonces de voitures électriques",
    annonceId: 2,
    userId: 108,
    createdAt: new Date("2023-10-08T10:15:00Z"),
  },
];
