export const users = [
  {
    userId: 1,
    firstName: "Chaker",
    lastName: "Yaakoub",
    email: "chaker.yaakoub@example.com",
    password: "password123",
    role: "buyer",
    type: "individual",
    phoneNumber: "+1234567890",
    country: "France",
    city: "Paris",
    urlImageUser: "https://res.cloudinary.com/dq87iplbt/image/upload/v1731975294/cqalstdlvp9n9jeihaux.png",
    unreadCountNotifications: 5,
    lastLogin: new Date("2023-10-01T12:00:00Z"),
    emailVerified: true,
    emailVerificationToken: null,
    emailVerificationTokenExpiration: null,
    passwordVerificationToken: null,
    passwordVerificationTokenExpiration: null,
    isActive: true,
    authProviderId: "google",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 2,
    firstName: "Mohamed",
    lastName: "ISMAEL OTBAN",
    email: "mohamed.ismael.otban@example.com",
    password: "securepassword",
    role: "vendor",
    type: "business",
    phoneNumber: "+0987654321",
    country: "France",
    city: "Lyon",
    urlImageUser: "https://res.cloudinary.com/dq87iplbt/image/upload/v1731968637/cshoourg4cbkbaat65fs.png",
    unreadCountNotifications: 2,
    lastLogin: new Date("2023-10-02T14:00:00Z"),
    emailVerified: true,
    emailVerificationToken: null,
    emailVerificationTokenExpiration: null,
    passwordVerificationToken: null,
    passwordVerificationTokenExpiration: null,
    isActive: true,
    authProviderId: "facebook",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
