export const colors = {
    primary: "#FFFFFF",
    secondary: "#EBEDF0",
    tertiary: "#2C3F55",
    accentTertiary: "#296DB1",
    accentGreen: "#388E3C",
    accentRed: "#FF0000",  
    accentGray: "#b0b0b0",
    textColor: "#333333",
    textOpacity: "#7C7C7C",
    textOpacityP: "#ABABAB",
    textOpacityPP: "#b7b7b7",
    inputColor: "#efefef",
    inputPlaceHolderColor: "rgba(0, 0, 0, 0.4)",
    æccentTertiaryMessage: "#CED4E0",
}
